{
 "title": "AirGradient",
 "time": { "from": "2024-12-19T08:00:00.000Z", "to": "2024-12-21T07:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Measuring Station",
    "query": {
     "query": "label_values(particulate_matter_1_0,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ambient Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(temperature_f{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(humidity{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(particulate_matter_2_5{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Particle Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(particulate_matter_count{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "LED Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "led_enabled{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Wifi Signal Strength",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wifi_signal_strength{device_name=\"airgradient\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Climate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ambient Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg(temperature_f{instance=\"$instance\"})",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(humidity{instance=\"$instance\"})",
     "legendFormat": "humidity"
    }
   ]
  },
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Particulate Matter (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(particulate_matter_count{instance=\"$instance\"})",
     "legendFormat": "pm count"
    }
   ]
  },
  {
   "title": "Particulate Matter 1",
   "type": "timeseries",
   "description": "Particulate matter 1 microns or less in diameter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "avg(particulate_matter_1_0{instance=\"$instance\"})",
     "legendFormat": "pm 1"
    }
   ]
  },
  {
   "title": "Particulate Matter 2.5",
   "type": "timeseries",
   "description": "Particulate matter 2.5 microns or less in diameter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "avg(particulate_matter_2_5{instance=\"$instance\"})",
     "legendFormat": "pm 2.5"
    }
   ]
  },
  {
   "title": "Particulate Matter 10",
   "type": "timeseries",
   "description": "Particulate matter 10 microns or less in diameter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "avg(particulate_matter_10_0{instance=\"$instance\"})",
     "legendFormat": "pm 10"
    }
   ]
  },
  { "title": "System Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Wifi Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wifi_signal_strength{instance=\"$instance\"}",
     "legendFormat": "signal strength"
    }
   ]
  }
 ]
}